dist: trusty
language: elixir
elixir: 1.4.2
otp_release: 19.2
addons:
  postgresql: 9.6
env:
  - MIX_ENV=test
script:
  - mix ecto.create
  - mix test --include integration
  - mix run priv/repo/seeds.exs
  - git clone https://github.com/hexpm/hex ../hex && cd ../hex && mix deps.get && mix test --include integration
notifications:
  recipients:
  - eric.meadows.jonsson@gmail.com
  slack:
    secure: D21dsphy22i/G+yujf1V4f2x9pnbmTr2BkZv3nifXggTXY+ObItQ2MM/j9AoObdusbV63eSpvBZTIfX/oe7DQjN8hHBc/aILMZMLq7gKpOCTLtWIVvS9vNkyLa33EWwF/CsMiYQh377vye8a7cvORlkPmf+rNV//E9mbpuIWzBI=
